create table collection_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('vinyls', 'cds', 'movies', 'books')),
  title text not null,
  creator text not null,
  year text,
  image text not null,
  link text,
  color text,
  edition text,
  format text,
  created_at timestamptz default now()
);

alter table collection_items add column if not exists link text;
alter table collection_items add column if not exists is_top4 boolean not null default false;
alter table collection_items add column if not exists top4_order integer;

create table if not exists top4_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('vinyls', 'cds', 'movies', 'books')),
  title text not null,
  creator text not null,
  year text,
  image text not null,
  link text,
  color text,
  edition text,
  format text,
  top4_order integer not null,
  created_at timestamptz default now()
);

alter table top4_items enable row level security;

create policy "Anyone can view top 4 items"
on top4_items for select to anon using (true);

create policy "Anyone can add top 4 items"
on top4_items for insert to anon with check (true);

create policy "Anyone can edit top 4 items"
on top4_items for update to anon using (true) with check (true);

create policy "Anyone can delete top 4 items"
on top4_items for delete to anon using (true);

alter table collection_items enable row level security;

create policy "Anyone can view collection items"
on collection_items for select
to anon using (true);

create policy "Anyone can add collection items"
on collection_items for insert
to anon with check (true);

create policy "Anyone can edit collection items"
on collection_items for update
to anon using (true) with check (true);

create policy "Anyone can delete collection items"
on collection_items for delete
to anon using (true);
