create table collection_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('vinyls', 'cds', 'movies', 'books')),
  title text not null,
  creator text not null,
  year text,
  image text not null,
  color text,
  edition text,
  format text,
  created_at timestamptz default now()
);

alter table collection_items enable row level security;

create policy "Anyone can view collection items"
on collection_items for select
to anon using (true);

create policy "Anyone can add collection items"
on collection_items for insert
to anon with check (true);

create policy "Anyone can edit collection items"
on collection_items for update
to anon using (true) with check (true);
